### ISSUE TITLE
Error on `unexpected(1) == unexpected(1L)`

### ISSUE THREAD

**Issue by Quuxplusone** [Quuxplusone/llvm-project#40]
https://godbolt.org/z/a8rPnKz1Y

    #include <expected>
    static_assert(std::unexpected(1) == std::unexpected(1L));

    __expected/unexpected.h:111:31: error: '__unex_' is a private member of 'std::unexpected<long>'
      111 |     return __x.__unex_ == __y.__unex_;
          |                               ^

The fix is to use `__y.error()` instead of `__y.__unex_`.

(attn: @huixie90)

**Comment by frederick-vs-ja** [comment]
I'm taking this.

**Comment by ldionne** [comment]
@Quuxplusone Some people may not be aware that you are affected by a ban from the LLVM community and what the process for handling this is (https://llvm.org/docs/DeveloperPolicy.html#bans), which can effectively lead people into breaking the LLVM Developer Policy without even knowing about it. I don't think that is your intention, but that's effectively what's happening.

For anyone reading: the process for handling contributions from a banned individual is laid out in https://llvm.org/docs/DeveloperPolicy.html#bans. It is important to avoid proxying communication for a banned individual (which would effectively circumvent their ban). Of course, that doesn't mean that we must ignore the existence of any such contribution (e.g. do as-if there was no bug in libc++ since it came from someone affected by a ban) -- that would make no sense. Instead, one must take full ownership and responsibility of the contribution, which I did in https://github.com/llvm/llvm-project/issues/115326. For any questions about what to do in these special situations, please contact the LLVM Code of Conduct committee -- I don't make the rules, they do.

I *really* don't like policing around, but I think it's better to have everything written down and clear than having a libc++ contributor be violating the developer policy without even knowing it.

**Comment by ldionne** [comment]
To be clear, the other alternative would be to conform to your ban and not try to contribute to libc++ via side channels. That would make a lot of things easier. But my role is not to police your online activity, it's to make sure that the libc++ project runs smoothly and according to the rules of the LLVM community. Since I feel like I've done that here, I don't have anything to add.

**Comment by Quuxplusone** [comment]
Fixed in llvm#115249!
